# Generated by Django 3.0.5 on 2020-05-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_stocks_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='stocks_owned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
