# Generated by Django 3.0.5 on 2020-05-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200505_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='buying_price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='stocks_owned',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
