# Generated by Django 3.0.5 on 2020-05-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200505_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='valuation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
